name: Build and Release Executables

on:
  push:
    branches:
      - main
  # You can also use workflow_dispatch to trigger manually
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyInstaller
          pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --windowed --name HDF5_BLS_GUI src/main.py

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDF5_BLS_GUI
          path: dist/
